language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get install gearman build-essential libevent-dev libboost-all-dev libgearman-dev
  - sudo ldconfig
  - pecl install gearman-0.8.3
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - phpunit -c phpunit.xml.dist --coverage-text

notifications:
    email: false
